### ISSUE TITLE
Vue: Cannot find module  @unhead/vue  or its corresponding type declarations

### ISSUE THREAD

**Issue by Nonolanlan1007** [unjs/unhead#182]
### Environment

Node.js : 18.12.1
NPM : 9.8.1
typescript : 5.1.6
Vue : 3.3.4
@unhead/vue : 1.2.1

### Reproduction

I have just followed the guide : https://unhead.harlanzw.com/integrations/vue/setup

### Describe the bug

When I add the import : `import { createHead } from '@unhead/vue';`, my IDE tells me : `Vue: Cannot find module  @unhead/vue  or its corresponding type declarations` and if I add `@ts-ignore`, it's work

**Comment by harlan-zw** [comment]
Could you see if this works in 1.4? It now generates proper types

**Comment by Nonolanlan1007** [comment]
I don't know why, now it's okay 😂 
Maybe a problem from Intellij 🤔
